- hosts: webserver01
  vars:
    nginx_port: 80
    root_dir: /var/tmp/www
  tasks:
    - name: UFW firewall Allow Nginx HTTP
      community.general.ufw:
        name: Nginx HTTP
        rule: allow
      become: true

    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
      become: true

    - name: Update HTML page
      ansible.builtin.copy:
        src: files/index.html
        dest: /usr/share/nginx/html/index.html
        mode: "0777"
      become: true

    - name: "Create directory {{ root_dir }}"
      ansible.builtin.file:
        path: "{{ root_dir }}"
        state: "directory"
        mode: "0777"
      become: true

    - name: Set new HTML page
      ansible.builtin.copy:
        src: files/index_2.html
        dest: "{{ root_dir }}/index.html"
        mode: "0777"
      become: true

    - name: Update nginx config
      ansible.builtin.template:
        src: files/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: "0777"
      notify:
        - Restart nginx
      become: true

  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: true
