- hosts: webserver01
  vars:
    nginx_port: 80
    root_dir: /var/tmp/www
    some_string: "This is server {{ ansible_hostname }}!"
  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
      become: true

    - name: UFW firewall Allow Nginx HTTP
      community.general.ufw:
        name: Nginx HTTP
        rule: allow
      become: true

    - name: "Create directory {{ root_dir }}"
      ansible.builtin.file:
        path: "{{ root_dir }}"
        state: "directory"
        mode: "0755"
      become: true

    - name: Set new HTML page
      ansible.builtin.template:
        src: files/html_with_filter.html.j2
        dest: "{{ root_dir }}/index.html"
        mode: "0644"
      become: true

    - name: Update nginx config
      ansible.builtin.template:
        src: files/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: "0644"
      notify:
        - Restart nginx
      become: true

  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: true
